name: Build

on: [push]

env:
  SolutionFolder: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Run npm ci
        run: npm ci
        working-directory: ${{ env.SolutionFolder }}

      - name: Run npm i -g gulp
        run: npm i -g gulp
        working-directory: ${{ env.SolutionFolder }}

      - name: Bundle and package
        run: |
          gulp bundle
          gulp package-solution
        working-directory: ${{ env.SolutionFolder }}
